// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package fabricatorgenerateapigo_test

import (
	"os"

	fabricatorgenerateapigo "code.cestus.io/tools/fabricator-generate-api-go/pkg/fabricator-generate-api-go"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Config", func() {
	It("Deserializes a fabricator config", func() {
		file, err := os.Open("./testdata/deserialize.yml")
		Expect(err).ToNot(HaveOccurred())
		config, err := fabricatorgenerateapigo.LoadPluginConfig(file)
		Expect(err).ToNot(HaveOccurred())
		expected := fabricatorgenerateapigo.PluginConfig{
			ApiVersion: "fabricator.cestus.io/v1alpha1",
			Kind:       "Config",
			Components: []fabricatorgenerateapigo.PluginComponent{
				{
					Name:      "fabricator-generate-api-go",
					Generator: "fabricator-generate-api-go",
					Spec: fabricatorgenerateapigo.Spec{
						PinDependency:     nil,
						ReplaceDependency: nil,
						ToolDependency:    nil,
					},
				},
			},
		}
		Expect(config).To(Equal(expected))
	})
})
