apiVersion: fabricator.cestus.io/v1alpha1
kind: Config
components:
  - name: fabricator-generate-api-go
    generator: fabricator-generate-go
    spec:
      packageName: fabricator-generate-api-go
  - name: fabricator-generate-api-go
    generator: fabricator-generate-project-go
    spec:
      goModule: code.cestus.io/tools/fabricator-generate-api-go
      repoURL: https://github.com/CestusIO/fabricator-generate-api-go
      isTool: true
  - name: fabricator-generate-api-go
    generator: fabricator-generate-plugin-go
    spec:
      pluginName: fabricator-generate-api-go
      isGenerationPlugin: true
